Newscoop\Entity\Comment:
    properties:
        ip:
            - Newscoop\CommentsBundle\Validator\Constraints\IPIsAllowed:
Newscoop\Entity\Comment\Commenter:
    properties:
        email:
            - Newscoop\CommentsBundle\Validator\Constraints\EmailIsAllowed: